name: Build DexDumper

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: r25b

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          echo "NDK_HOME=$PWD/android-ndk-r25b" >> $GITHUB_ENV

      - name: Find DexDumper
        run: |
          find . -name Android.mk
          find . -name Application.mk

      - name: Build
        run: |
          cd dexdumper

          $NDK_HOME/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=./jni/Android.mk \
            NDK_APPLICATION_MK=./jni/Application.mk \
            APP_PLATFORM=android-21

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: DexDumper
          path: dexdumper/libs
