name: Flutter Build SO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Flutter version
        run: flutter --version

      - name: Create Flutter project
        run: |
          flutter create flutter_so
          cd flutter_so
          flutter pub get

      - name: Build native libraries
        run: |
          cd flutter_so
          flutter build apk --release \
            --target-platform android-arm,android-arm64

      - name: Upload arm64 libflutter.so
        uses: actions/upload-artifact@v4
        with:
          name: libflutter_so_arm64
          path: flutter_so/build/app/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libflutter.so

      - name: Upload armeabi-v7a libflutter.so
        uses: actions/upload-artifact@v4
        with:
          name: libflutter_so_armeabi_v7a
          path: flutter_so/build/app/intermediates/merged_native_libs/release/out/lib/armeabi-v7a/libflutter.so
